package pojo;

public class HxAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_admin.adminid
     *
     * @mbggenerated
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_admin.adminname
     *
     * @mbggenerated
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_admin.adminpwd
     *
     * @mbggenerated
     */
    private String adminpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_admin.adminemail
     *
     * @mbggenerated
     */
    private String adminemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_admin.adminphone
     *
     * @mbggenerated
     */
    private String adminphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_admin.adminid
     *
     * @return the value of hx_admin.adminid
     *
     * @mbggenerated
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_admin.adminid
     *
     * @param adminid the value for hx_admin.adminid
     *
     * @mbggenerated
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_admin.adminname
     *
     * @return the value of hx_admin.adminname
     *
     * @mbggenerated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_admin.adminname
     *
     * @param adminname the value for hx_admin.adminname
     *
     * @mbggenerated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_admin.adminpwd
     *
     * @return the value of hx_admin.adminpwd
     *
     * @mbggenerated
     */
    public String getAdminpwd() {
        return adminpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_admin.adminpwd
     *
     * @param adminpwd the value for hx_admin.adminpwd
     *
     * @mbggenerated
     */
    public void setAdminpwd(String adminpwd) {
        this.adminpwd = adminpwd == null ? null : adminpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_admin.adminemail
     *
     * @return the value of hx_admin.adminemail
     *
     * @mbggenerated
     */
    public String getAdminemail() {
        return adminemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_admin.adminemail
     *
     * @param adminemail the value for hx_admin.adminemail
     *
     * @mbggenerated
     */
    public void setAdminemail(String adminemail) {
        this.adminemail = adminemail == null ? null : adminemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_admin.adminphone
     *
     * @return the value of hx_admin.adminphone
     *
     * @mbggenerated
     */
    public String getAdminphone() {
        return adminphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_admin.adminphone
     *
     * @param adminphone the value for hx_admin.adminphone
     *
     * @mbggenerated
     */
    public void setAdminphone(String adminphone) {
        this.adminphone = adminphone == null ? null : adminphone.trim();
    }
}