package pojo;

public class HxArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.parentId
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.short_name
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.level_type
     *
     * @mbggenerated
     */
    private Integer levelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.zip_code
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.merger_name
     *
     * @mbggenerated
     */
    private String mergerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.lng
     *
     * @mbggenerated
     */
    private Float lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.lat
     *
     * @mbggenerated
     */
    private Float lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_area.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.id
     *
     * @return the value of hx_area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.id
     *
     * @param id the value for hx_area.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.name
     *
     * @return the value of hx_area.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.name
     *
     * @param name the value for hx_area.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.parentId
     *
     * @return the value of hx_area.parentId
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.parentId
     *
     * @param parentid the value for hx_area.parentId
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.short_name
     *
     * @return the value of hx_area.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.short_name
     *
     * @param shortName the value for hx_area.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.level_type
     *
     * @return the value of hx_area.level_type
     *
     * @mbggenerated
     */
    public Integer getLevelType() {
        return levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.level_type
     *
     * @param levelType the value for hx_area.level_type
     *
     * @mbggenerated
     */
    public void setLevelType(Integer levelType) {
        this.levelType = levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.city_code
     *
     * @return the value of hx_area.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.city_code
     *
     * @param cityCode the value for hx_area.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.zip_code
     *
     * @return the value of hx_area.zip_code
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.zip_code
     *
     * @param zipCode the value for hx_area.zip_code
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.merger_name
     *
     * @return the value of hx_area.merger_name
     *
     * @mbggenerated
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.merger_name
     *
     * @param mergerName the value for hx_area.merger_name
     *
     * @mbggenerated
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName == null ? null : mergerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.lng
     *
     * @return the value of hx_area.lng
     *
     * @mbggenerated
     */
    public Float getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.lng
     *
     * @param lng the value for hx_area.lng
     *
     * @mbggenerated
     */
    public void setLng(Float lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.lat
     *
     * @return the value of hx_area.lat
     *
     * @mbggenerated
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.lat
     *
     * @param lat the value for hx_area.lat
     *
     * @mbggenerated
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_area.pinyin
     *
     * @return the value of hx_area.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_area.pinyin
     *
     * @param pinyin the value for hx_area.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}