package pojo;

public class HxCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companyid
     *
     * @mbggenerated
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companyaccount
     *
     * @mbggenerated
     */
    private String companyaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companypwd
     *
     * @mbggenerated
     */
    private String companypwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companysalt
     *
     * @mbggenerated
     */
    private String companysalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companyname
     *
     * @mbggenerated
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.addressid
     *
     * @mbggenerated
     */
    private Integer addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companyphone
     *
     * @mbggenerated
     */
    private String companyphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companytypeid
     *
     * @mbggenerated
     */
    private Integer companytypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companylicenseurl
     *
     * @mbggenerated
     */
    private String companylicenseurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companyemail
     *
     * @mbggenerated
     */
    private String companyemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companyregtime
     *
     * @mbggenerated
     */
    private String companyregtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_company.companyinformation
     *
     * @mbggenerated
     */
    private String companyinformation;

    private int typevalueid;
    private int companyRecruitCount;

    public int getCompanyRecruitCount() {
        return companyRecruitCount;
    }

    public void setCompanyRecruitCount(int companyRecruitCount) {
        this.companyRecruitCount = companyRecruitCount;
    }

    public int getTypevalueid() {
        return typevalueid;
    }

    public void setTypevalueid(int typevalueid) {
        this.typevalueid = typevalueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companyid
     *
     * @return the value of hx_company.companyid
     *
     * @mbggenerated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companyid
     *
     * @param companyid the value for hx_company.companyid
     *
     * @mbggenerated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companyaccount
     *
     * @return the value of hx_company.companyaccount
     *
     * @mbggenerated
     */
    public String getCompanyaccount() {
        return companyaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companyaccount
     *
     * @param companyaccount the value for hx_company.companyaccount
     *
     * @mbggenerated
     */
    public void setCompanyaccount(String companyaccount) {
        this.companyaccount = companyaccount == null ? null : companyaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companypwd
     *
     * @return the value of hx_company.companypwd
     *
     * @mbggenerated
     */
    public String getCompanypwd() {
        return companypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companypwd
     *
     * @param companypwd the value for hx_company.companypwd
     *
     * @mbggenerated
     */
    public void setCompanypwd(String companypwd) {
        this.companypwd = companypwd == null ? null : companypwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companysalt
     *
     * @return the value of hx_company.companysalt
     *
     * @mbggenerated
     */
    public String getCompanysalt() {
        return companysalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companysalt
     *
     * @param companysalt the value for hx_company.companysalt
     *
     * @mbggenerated
     */
    public void setCompanysalt(String companysalt) {
        this.companysalt = companysalt == null ? null : companysalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companyname
     *
     * @return the value of hx_company.companyname
     *
     * @mbggenerated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companyname
     *
     * @param companyname the value for hx_company.companyname
     *
     * @mbggenerated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.addressid
     *
     * @return the value of hx_company.addressid
     *
     * @mbggenerated
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.addressid
     *
     * @param addressid the value for hx_company.addressid
     *
     * @mbggenerated
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companyphone
     *
     * @return the value of hx_company.companyphone
     *
     * @mbggenerated
     */
    public String getCompanyphone() {
        return companyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companyphone
     *
     * @param companyphone the value for hx_company.companyphone
     *
     * @mbggenerated
     */
    public void setCompanyphone(String companyphone) {
        this.companyphone = companyphone == null ? null : companyphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companytypeid
     *
     * @return the value of hx_company.companytypeid
     *
     * @mbggenerated
     */
    public Integer getCompanytypeid() {
        return companytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companytypeid
     *
     * @param companytypeid the value for hx_company.companytypeid
     *
     * @mbggenerated
     */
    public void setCompanytypeid(Integer companytypeid) {
        this.companytypeid = companytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companylicenseurl
     *
     * @return the value of hx_company.companylicenseurl
     *
     * @mbggenerated
     */
    public String getCompanylicenseurl() {
        return companylicenseurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companylicenseurl
     *
     * @param companylicenseurl the value for hx_company.companylicenseurl
     *
     * @mbggenerated
     */
    public void setCompanylicenseurl(String companylicenseurl) {
        this.companylicenseurl = companylicenseurl == null ? null : companylicenseurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companyemail
     *
     * @return the value of hx_company.companyemail
     *
     * @mbggenerated
     */
    public String getCompanyemail() {
        return companyemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companyemail
     *
     * @param companyemail the value for hx_company.companyemail
     *
     * @mbggenerated
     */
    public void setCompanyemail(String companyemail) {
        this.companyemail = companyemail == null ? null : companyemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companyregtime
     *
     * @return the value of hx_company.companyregtime
     *
     * @mbggenerated
     */
    public String getCompanyregtime() {
        return companyregtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companyregtime
     *
     * @param companyregtime the value for hx_company.companyregtime
     *
     * @mbggenerated
     */
    public void setCompanyregtime(String companyregtime) {
        this.companyregtime = companyregtime == null ? null : companyregtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_company.companyinformation
     *
     * @return the value of hx_company.companyinformation
     *
     * @mbggenerated
     */
    public String getCompanyinformation() {
        return companyinformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_company.companyinformation
     *
     * @param companyinformation the value for hx_company.companyinformation
     *
     * @mbggenerated
     */
    public void setCompanyinformation(String companyinformation) {
        this.companyinformation = companyinformation == null ? null : companyinformation.trim();
    }
}