package pojo;

public class HxCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_collection.seekerid
     *
     * @mbggenerated
     */
    private Integer seekerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_collection.companyid
     *
     * @mbggenerated
     */
    private Integer companyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_collection.seekerid
     *
     * @return the value of hx_collection.seekerid
     *
     * @mbggenerated
     */
    public Integer getSeekerid() {
        return seekerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_collection.seekerid
     *
     * @param seekerid the value for hx_collection.seekerid
     *
     * @mbggenerated
     */
    public void setSeekerid(Integer seekerid) {
        this.seekerid = seekerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_collection.companyid
     *
     * @return the value of hx_collection.companyid
     *
     * @mbggenerated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_collection.companyid
     *
     * @param companyid the value for hx_collection.companyid
     *
     * @mbggenerated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
}