package pojo;

public class HxDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_dictionary.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_dictionary.typename
     *
     * @mbggenerated
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_dictionary.typevalueid
     *
     * @mbggenerated
     */
    private Integer typevalueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_dictionary.valuename
     *
     * @mbggenerated
     */
    private String valuename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_dictionary.id
     *
     * @return the value of hx_dictionary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_dictionary.id
     *
     * @param id the value for hx_dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_dictionary.typename
     *
     * @return the value of hx_dictionary.typename
     *
     * @mbggenerated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_dictionary.typename
     *
     * @param typename the value for hx_dictionary.typename
     *
     * @mbggenerated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_dictionary.typevalueid
     *
     * @return the value of hx_dictionary.typevalueid
     *
     * @mbggenerated
     */
    public Integer getTypevalueid() {
        return typevalueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_dictionary.typevalueid
     *
     * @param typevalueid the value for hx_dictionary.typevalueid
     *
     * @mbggenerated
     */
    public void setTypevalueid(Integer typevalueid) {
        this.typevalueid = typevalueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_dictionary.valuename
     *
     * @return the value of hx_dictionary.valuename
     *
     * @mbggenerated
     */
    public String getValuename() {
        return valuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_dictionary.valuename
     *
     * @param valuename the value for hx_dictionary.valuename
     *
     * @mbggenerated
     */
    public void setValuename(String valuename) {
        this.valuename = valuename == null ? null : valuename.trim();
    }
}