package pojo;

public class HxResumeOfCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_resume_of_company.campanyid
     *
     * @mbggenerated
     */
    private Integer campanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_resume_of_company.resumeid
     *
     * @mbggenerated
     */
    private Integer resumeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_resume_of_company.campanyid
     *
     * @return the value of hx_resume_of_company.campanyid
     *
     * @mbggenerated
     */
    public Integer getCampanyid() {
        return campanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_resume_of_company.campanyid
     *
     * @param campanyid the value for hx_resume_of_company.campanyid
     *
     * @mbggenerated
     */
    public void setCampanyid(Integer campanyid) {
        this.campanyid = campanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_resume_of_company.resumeid
     *
     * @return the value of hx_resume_of_company.resumeid
     *
     * @mbggenerated
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_resume_of_company.resumeid
     *
     * @param resumeid the value for hx_resume_of_company.resumeid
     *
     * @mbggenerated
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }
}